
--Borrar tablespace
--ROP TABLESPACE NOMBRE_TABLESPACE_IDX;


CREATE TABLESPACE TEST_DATA LOGGING
DATAFILE 'C:\oracleXE\oradata\XE\test_db/TEST_DATA.dbf' SIZE 1M
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TEST_DATA_IDX LOGGING DATAFILE 
'C:\oracleXE\oradata\XE\test_db/TEST_DATA_IDX.dbf' SIZE 1M 
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER test_user 
PROFILE DEFAULT IDENTIFIED BY 
test_user DEFAULT TABLESPACE 
TEST_DATA TEMPORARY TABLESPACE 
TEMP ACCOUNT UNLOCK;

--Para usarlo no olvidar darle PERMISOS DE CONEXION
GRANT CONNECT TO test_user;
GRANT RESOURCE TO test_user;
ALTER USER test_user QUOTA UNLIMITED ON TEST_DATA;

--CREATE INDEX IX_CLIENTE_NOMBRE ON CLIENTE(NOMBRE) 
--TABLESPACE TEST_DATA_IDX;

 select * from dba_users;